---
# File:    main.yml
# Purpose:  playbook to deploy webpagetest
#

- name: wptServer deployment
  hosts: wptServer
  vars:
  	host_name: 192.168.33.33
    port_no: 8080
    wpt_version: 2.18
  sudo: true
  roles:
     - webpagetest
